[config]
schemaVersion = "0.0.1"

[package]
namespace = "XoXFaby"
name = "BetterAPI"
versionNumber = "2.0.0"
description = "A simple API implementation"
websiteUrl = "https://github.com/xoxfaby/BetterAPI"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.9"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../zip"

[[build.copy]]
source = "../bin/Release/netstandard2.0/BetterAPI.dll"
target = "BetterAPI.dll"

[[build.copy]]
source = "../bin/Release/netstandard2.0/publish/BetterUnityPlugin.dll"
target = "BetterUnityPlugin.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["Risk of Rain2"]
categories = ["Mods", "Libraries"]