name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLABot:
    if: github.event_name == 'pull_request_target' || contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Signature Bot"
        uses: MetaMask/cla-signature-bot@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'main'
          allowlist: 'xoxfaby' 
          url-to-cladocument: 'https://github.com/xoxfaby/BetterAPI/blob/main/CLA.md'
